server:
  port: 8101

spring:
  application:
    name: monitoring-trace-example-reactive

aryee:
  monitoring:
    reactive:
      enabled: true
      metrics:
        enabled: false
      alerts:
        enabled: false
      logs:
        enabled: false
      tracing:
        enabled: true
        service-name: ${spring.application.name}
        trace-id-header: traceparent
        fallback-trace-id-headers:
          - X-B3-TraceId
          - x-trace-id
        fallback-span-id-headers:
          - X-B3-SpanId
        response-trace-id-header: x-trace-id
        exclude-patterns:
          - /actuator/**
          - /error

management:
  endpoints:
    web:
      exposure:
        include: health,info
